name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: |
        python src/train.py
        python src/evaluate.py

    - name: Build Docker image
      run: docker build -t heart-attack-mlops .

    - name: Push Docker image to registry
      run: echo "Push logic here"